version: '3'
networks:
  bandwith-network:
    driver: bridge
services:
  bandwith-mongodb:
    image: mongo:latest
    container_name: bandwith-mongodb
    restart: unless-stopped
    expose:
      - 27017
    volumes:
      - ./data/mongodb:/data/db:rw
      - ./data/mongoconfigdb:/data/configdb:rw
    networks:
      - bandwith-network

  bandwith:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    container_name: bandwith
    env_file: .env
    hostname: bandwith
    volumes:
      - ./logs:/root/server/logs:rw
    networks:
      - bandwith-network
    ports:
      - '1380:80'
      - '44422:22'
    depends_on:
      - bandwith-mongodb
    links:
      - bandwith-mongodb
